# The URL the site will be built for
base_url = "/no/submodule/university_8988a097-b948-46f0-a5c5-cbe50a32949f/content/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "en"

[languages]
[languages.no]
build_search_index = true

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
